;;; doom-moss-theme.el --- Muted pixel-art moss and ruins (light) -*- no-byte-compile: t; -*-
;;; Commentary:
;;; Same palette as ~/System/dotfiles/themes/moss.conf: sage-grey background, dark teal
;;; text, olive/moss greens, tan, and the red cloak as the warm accent.
;;; Code:
(require 'doom-themes)

(def-doom-theme doom-moss
    "Moss: sage grey, teal, olive, tan, one red cloak."

  ;; name        default   256       16
  ((bg         '("#d0d2c7" nil       nil            ))
   (bg-alt     '("#c6c8bb" nil       nil            ))
   (base0      '("#c6c8bb" "black"   "black"        ))
   (base1      '("#c0c2b3" nil       nil            ))
   (base2      '("#b8baa9" nil       nil            ))
   (base3      '("#b5b4a2" nil       nil            ))
   (base4      '("#9a9f8c" nil       nil            ))
   (base5      '("#807c69" nil       nil            ))
   (base6      '("#6f735f" nil       nil            ))
   (base7      '("#565a4b" nil       nil            ))
   (base8      '("#1d332d" "white"   "white"        ))
   (fg         '("#2e4d45" "white"   "white"        ))
   (fg-alt     '("#475e4e" "white"   "white"        ))

   (grey       base5)
   (red        '("#a8403c" "#a8403c" "red"          ))
   (orange     '("#8a6a3a" "#8a6a3a" "brightred"    ))
   (green      '("#656832" "#656832" "green"        ))
   (teal       '("#4a8a78" "#4a8a78" "brightgreen"  ))
   (yellow     '("#8a6a1f" "#8a6a1f" "yellow"       ))
   (blue       '("#3d6b5a" "#3d6b5a" "brightblue"   ))
   (dark-blue  '("#2e4d45" "#2e4d45" "blue"         ))
   (magenta    '("#9c5754" "#9c5754" "magenta"      ))
   (violet     '("#7a5a6a" "#7a5a6a" "brightmagenta"))
   (cyan       '("#3d6b5a" "#3d6b5a" "brightcyan"   ))
   (dark-cyan  '("#2e5d52" "#2e5d52" "cyan"         ))

   ;; accents for document structure (headings, links, quotes, tags)
   (coral      '("#9c5754" "#9c5754" "red"          ))
   (gold       '("#8a6a1f" "#8a6a1f" "yellow"       ))
   (sage       '("#656832" "#656832" "green"        ))
   (peach      '("#8a6a3a" "#8a6a3a" "brightred"    ))
   (aqua       '("#3d6b5a" "#3d6b5a" "cyan"         ))
   (rose       '("#7a5a6a" "#7a5a6a" "magenta"      ))

   ;; face categories -- required for all themes
   (highlight      magenta)
   (vertical-bar   base4)
   (selection      base3)
   (builtin        violet)
   (comments       base5)
   (doc-comments   base6)
   (constants      orange)
   (functions      cyan)
   (keywords       magenta)
   (methods        cyan)
   (operators      base7)
   (type           base7)
   (strings        green)
   (variables      fg)
   (numbers        orange)
   (region         base3)
   (error          red)
   (warning        orange)
   (success        green)
   (vc-modified    violet)
   (vc-added       green)
   (vc-deleted     red)

   (modeline-fg     '("#e9eadf" "white" "white"))
   (modeline-bg     '("#475e4e" nil nil))
   (modeline-bg-inactive base1))

  ;; --- extra faces ------------------------
  (((line-number &override) :foreground base4)
   ((line-number-current-line &override) :foreground fg :weight 'bold)
   ((font-lock-keyword-face &override) :weight 'bold)
   ((font-lock-function-name-face &override) :weight 'bold)
   (cursor :background fg)
   ;; inverted mode-line, like the selected tag in the dwm bar
   (mode-line :background modeline-bg :foreground modeline-fg)
   (mode-line-inactive :background modeline-bg-inactive :foreground base6)
   (doom-modeline-bar :background bg)
   (doom-modeline-buffer-file :foreground modeline-fg :weight 'bold)
   (doom-modeline-buffer-path :foreground modeline-fg)
   (doom-modeline-project-dir :foreground modeline-fg :weight 'bold)
   (doom-modeline-info :foreground modeline-fg)
   ;; dired: same idea as ls in the terminal
   (dired-directory :foreground blue :weight 'bold)
   (dired-symlink :foreground dark-cyan :weight 'bold :underline t)
   ;; headings: one hue per level (org and markdown share them)
   (outline-1 :foreground base8 :weight 'bold)
   (outline-2 :foreground coral :weight 'bold)
   (outline-3 :foreground gold  :weight 'bold)
   (outline-4 :foreground sage  :weight 'bold)
   (outline-5 :foreground peach :weight 'bold)
   (outline-6 :foreground aqua  :weight 'bold)
   (outline-7 :foreground rose  :weight 'bold)
   (outline-8 :foreground base7 :weight 'bold)
   ((org-level-1 &override) :inherit 'outline-1 :foreground base8)
   ((org-level-2 &override) :inherit 'outline-2 :foreground coral)
   ((org-level-3 &override) :inherit 'outline-3 :foreground gold)
   ((org-level-4 &override) :inherit 'outline-4 :foreground sage)
   ((org-level-5 &override) :inherit 'outline-5 :foreground peach)
   ((org-level-6 &override) :inherit 'outline-6 :foreground aqua)
   (markdown-header-face-1 :inherit 'outline-1)
   (markdown-header-face-2 :inherit 'outline-2)
   (markdown-header-face-3 :inherit 'outline-3)
   (markdown-header-face-4 :inherit 'outline-4)
   (markdown-header-face-5 :inherit 'outline-5)
   (markdown-header-face-6 :inherit 'outline-6)
   (markdown-header-delimiter-face :foreground base5)
   ;; inline structure
   (link :foreground aqua :underline t)
   (org-link :foreground aqua :underline t)
   (markdown-link-face :foreground aqua)
   (markdown-url-face :foreground base6 :underline t)
   (markdown-bold-face :foreground base8 :weight 'bold)
   (markdown-italic-face :foreground gold :slant 'italic)
   (markdown-inline-code-face :foreground peach :background base1)
   ((org-code &override) :foreground peach)
   (markdown-blockquote-face :foreground sage :slant 'italic)
   ((org-quote &override) :foreground sage :slant 'italic)
   (markdown-list-face :foreground coral)
   (markdown-gfm-checkbox-face :foreground gold :weight 'bold)
   (markdown-metadata-key-face :foreground coral)
   (markdown-metadata-value-face :foreground fg-alt)
   ((org-tag &override) :foreground sage)
   ((org-document-title &override) :foreground base8 :weight 'bold)))

;;; doom-moss-theme.el ends here
