;;; doom-overdose-theme.el --- Needy Girl Overdose pastel (light) -*- no-byte-compile: t; -*-
;;; Commentary:
;;; Same palette as ~/System/dotfiles/themes/overdose.conf: pale pink/lilac background,
;;; indigo text, royal-blue + cyan frames, magenta/pink highlights.
;;; Code:
(require 'doom-themes)

(def-doom-theme doom-overdose
    "Needy Girl Overdose: light pastel pink, lilac, royal blue."

  ;; name        default   256       16
  ((bg         '("#fbf0fc" nil       nil            ))
   (bg-alt     '("#f3ddf6" nil       nil            ))
   (base0      '("#f3ddf6" "black"   "black"        ))
   (base1      '("#ecd3f5" nil       nil            ))
   (base2      '("#e2c8f2" nil       nil            ))
   (base3      '("#d6d2fa" nil       nil            ))
   (base4      '("#a3a0eb" nil       nil            ))
   (base5      '("#9b8fce" nil       nil            ))
   (base6      '("#7a6fc8" nil       nil            ))
   (base7      '("#6652bc" nil       nil            ))
   (base8      '("#1e1462" "white"   "white"        ))
   (fg         '("#3a2a8f" "white"   "white"        ))
   (fg-alt     '("#6652bc" "white"   "white"        ))

   (grey       base5)
   (red        '("#d6245e" "#d6245e" "red"          ))
   (orange     '("#c77012" "#c77012" "brightred"    ))
   (green      '("#2a9a8a" "#2a9a8a" "green"        ))
   (teal       '("#1f8fc8" "#1f8fc8" "brightgreen"  ))
   (yellow     '("#b0801a" "#b0801a" "yellow"       ))
   (blue       '("#6061e7" "#6061e7" "brightblue"   ))
   (dark-blue  '("#4c24cf" "#4c24cf" "blue"         ))
   (magenta    '("#d6338a" "#d6338a" "magenta"      ))
   (violet     '("#9d60d9" "#9d60d9" "brightmagenta"))
   (cyan       '("#1f8fc8" "#1f8fc8" "brightcyan"   ))
   (dark-cyan  '("#177aa8" "#177aa8" "cyan"         ))

   ;; accents for document structure (headings, links, quotes, tags)
   (coral      '("#d6338a" "#d6338a" "red"          ))
   (gold       '("#c77012" "#c77012" "yellow"       ))
   (sage       '("#2a9a8a" "#2a9a8a" "green"        ))
   (peach      '("#e0628a" "#e0628a" "brightred"    ))
   (aqua       '("#1f8fc8" "#1f8fc8" "cyan"         ))
   (rose       '("#c43fc9" "#c43fc9" "magenta"      ))

   ;; face categories -- required for all themes
   (highlight      magenta)
   (vertical-bar   base4)
   (selection      base3)
   (builtin        violet)
   (comments       base5)
   (doc-comments   base6)
   (constants      orange)
   (functions      cyan)
   (keywords       magenta)
   (methods        cyan)
   (operators      base7)
   (type           base7)
   (strings        green)
   (variables      fg)
   (numbers        orange)
   (region         base3)
   (error          red)
   (warning        orange)
   (success        green)
   (vc-modified    violet)
   (vc-added       green)
   (vc-deleted     red)

   (modeline-fg     '("#ffffff" "white" "white"))
   (modeline-bg     blue)
   (modeline-bg-inactive base1))

  ;; --- extra faces ------------------------
  (((line-number &override) :foreground base4)
   ((line-number-current-line &override) :foreground fg :weight 'bold)
   ((font-lock-keyword-face &override) :weight 'bold)
   ((font-lock-function-name-face &override) :weight 'bold)
   (cursor :background fg)
   ;; inverted mode-line, like the selected tag in the dwm bar
   (mode-line :background modeline-bg :foreground modeline-fg)
   (mode-line-inactive :background modeline-bg-inactive :foreground base6)
   (doom-modeline-bar :background bg)
   (doom-modeline-buffer-file :foreground modeline-fg :weight 'bold)
   (doom-modeline-buffer-path :foreground modeline-fg)
   (doom-modeline-project-dir :foreground modeline-fg :weight 'bold)
   (doom-modeline-info :foreground modeline-fg)
   ;; dired: same idea as ls in the terminal
   (dired-directory :foreground blue :weight 'bold)
   (dired-symlink :foreground dark-cyan :weight 'bold :underline t)
   ;; headings: one hue per level (org and markdown share them)
   (outline-1 :foreground base8 :weight 'bold)
   (outline-2 :foreground coral :weight 'bold)
   (outline-3 :foreground gold  :weight 'bold)
   (outline-4 :foreground sage  :weight 'bold)
   (outline-5 :foreground peach :weight 'bold)
   (outline-6 :foreground aqua  :weight 'bold)
   (outline-7 :foreground rose  :weight 'bold)
   (outline-8 :foreground base7 :weight 'bold)
   ((org-level-1 &override) :inherit 'outline-1 :foreground base8)
   ((org-level-2 &override) :inherit 'outline-2 :foreground coral)
   ((org-level-3 &override) :inherit 'outline-3 :foreground gold)
   ((org-level-4 &override) :inherit 'outline-4 :foreground sage)
   ((org-level-5 &override) :inherit 'outline-5 :foreground peach)
   ((org-level-6 &override) :inherit 'outline-6 :foreground aqua)
   (markdown-header-face-1 :inherit 'outline-1)
   (markdown-header-face-2 :inherit 'outline-2)
   (markdown-header-face-3 :inherit 'outline-3)
   (markdown-header-face-4 :inherit 'outline-4)
   (markdown-header-face-5 :inherit 'outline-5)
   (markdown-header-face-6 :inherit 'outline-6)
   (markdown-header-delimiter-face :foreground base5)
   ;; inline structure
   (link :foreground aqua :underline t)
   (org-link :foreground aqua :underline t)
   (markdown-link-face :foreground aqua)
   (markdown-url-face :foreground base6 :underline t)
   (markdown-bold-face :foreground base8 :weight 'bold)
   (markdown-italic-face :foreground gold :slant 'italic)
   (markdown-inline-code-face :foreground peach :background base1)
   ((org-code &override) :foreground peach)
   (markdown-blockquote-face :foreground sage :slant 'italic)
   ((org-quote &override) :foreground sage :slant 'italic)
   (markdown-list-face :foreground coral)
   (markdown-gfm-checkbox-face :foreground gold :weight 'bold)
   (markdown-metadata-key-face :foreground coral)
   (markdown-metadata-value-face :foreground fg-alt)
   ((org-tag &override) :foreground sage)
   ((org-document-title &override) :foreground base8 :weight 'bold)))

;;; doom-overdose-theme.el ends here
