;;; doom-vapor-night-theme.el --- Vaporwave night purple -*- no-byte-compile: t; -*-
;;; Commentary:
;;; Same palette as ~/System/dotfiles/themes/vapor.conf (alacritty / dwm / firefox / vscode):
;;; night-purple background, lavender text, pink + cyan glitch accents.
;;; Code:
(require 'doom-themes)

(def-doom-theme doom-vapor-night
    "Vaporwave night: purple, lavender, pink/cyan glitch."

  ;; name        default   256       16
  ((bg         '("#1e1838" nil       nil            ))
   (bg-alt     '("#17122c" nil       nil            ))
   (base0      '("#17122c" "black"   "black"        ))
   (base1      '("#2a2350" nil       nil            ))
   (base2      '("#342b60" nil       nil            ))
   (base3      '("#3f3570" nil       nil            ))
   (base4      '("#4b4298" nil       nil            ))
   (base5      '("#7b75a7" nil       nil            ))
   (base6      '("#9e9dc6" nil       nil            ))
   (base7      '("#a999db" nil       nil            ))
   (base8      '("#f5f0ff" "white"   "white"        ))
   (fg         '("#ddd5f1" "white"   "white"        ))
   (fg-alt     '("#ceb5f3" "white"   "white"        ))

   (grey       base5)
   (red        '("#ff5c7a" "#ff5c7a" "red"          ))
   (orange     '("#ffb86c" "#ffb86c" "brightred"    ))
   (green      '("#8be9c8" "#8be9c8" "green"        ))
   (teal       '("#a3f0f7" "#a3f0f7" "brightgreen"  ))
   (yellow     '("#ffd98c" "#ffd98c" "yellow"       ))
   (blue       '("#a7a0ff" "#a7a0ff" "brightblue"   ))
   (dark-blue  '("#8a7ff0" "#8a7ff0" "blue"         ))
   (magenta    '("#ff6fa5" "#ff6fa5" "magenta"      ))
   (violet     '("#d49bf0" "#d49bf0" "brightmagenta"))
   (cyan       '("#6fe3f0" "#6fe3f0" "brightcyan"   ))
   (dark-cyan  '("#5ab8c7" "#5ab8c7" "cyan"         ))

   ;; accents for document structure (headings, links, quotes, tags)
   (coral      '("#ff6fa5" "#ff6fa5" "red"          ))
   (gold       '("#ffd98c" "#ffd98c" "yellow"       ))
   (sage       '("#8be9c8" "#8be9c8" "green"        ))
   (peach      '("#ffb86c" "#ffb86c" "brightred"    ))
   (aqua       '("#6fe3f0" "#6fe3f0" "cyan"         ))
   (rose       '("#e6b8ff" "#e6b8ff" "magenta"      ))

   ;; face categories -- required for all themes
   (highlight      magenta)
   (vertical-bar   base4)
   (selection      base3)
   (builtin        violet)
   (comments       base5)
   (doc-comments   base6)
   (constants      orange)
   (functions      cyan)
   (keywords       magenta)
   (methods        cyan)
   (operators      base7)
   (type           fg-alt)
   (strings        green)
   (variables      fg)
   (numbers        orange)
   (region         base3)
   (error          red)
   (warning        orange)
   (success        green)
   (vc-modified    violet)
   (vc-added       green)
   (vc-deleted     red)

   (modeline-fg     base8)
   (modeline-bg     base4)
   (modeline-bg-inactive base1))

  ;; --- extra faces ------------------------
  (((line-number &override) :foreground base4)
   ((line-number-current-line &override) :foreground fg :weight 'bold)
   ((font-lock-keyword-face &override) :weight 'bold)
   ((font-lock-function-name-face &override) :weight 'bold)
   (cursor :background fg)
   ;; inverted mode-line, like the selected tag in the dwm bar
   (mode-line :background modeline-bg :foreground modeline-fg)
   (mode-line-inactive :background modeline-bg-inactive :foreground base6)
   (doom-modeline-bar :background bg)
   (doom-modeline-buffer-file :foreground modeline-fg :weight 'bold)
   (doom-modeline-buffer-path :foreground modeline-fg)
   (doom-modeline-project-dir :foreground modeline-fg :weight 'bold)
   (doom-modeline-info :foreground modeline-fg)
   ;; dired: same idea as ls in the terminal
   (dired-directory :foreground blue :weight 'bold)
   (dired-symlink :foreground dark-cyan :weight 'bold :underline t)
   ;; headings: one hue per level (org and markdown share them)
   (outline-1 :foreground base8 :weight 'bold)
   (outline-2 :foreground coral :weight 'bold)
   (outline-3 :foreground gold  :weight 'bold)
   (outline-4 :foreground sage  :weight 'bold)
   (outline-5 :foreground peach :weight 'bold)
   (outline-6 :foreground aqua  :weight 'bold)
   (outline-7 :foreground rose  :weight 'bold)
   (outline-8 :foreground base7 :weight 'bold)
   ((org-level-1 &override) :inherit 'outline-1 :foreground base8)
   ((org-level-2 &override) :inherit 'outline-2 :foreground coral)
   ((org-level-3 &override) :inherit 'outline-3 :foreground gold)
   ((org-level-4 &override) :inherit 'outline-4 :foreground sage)
   ((org-level-5 &override) :inherit 'outline-5 :foreground peach)
   ((org-level-6 &override) :inherit 'outline-6 :foreground aqua)
   (markdown-header-face-1 :inherit 'outline-1)
   (markdown-header-face-2 :inherit 'outline-2)
   (markdown-header-face-3 :inherit 'outline-3)
   (markdown-header-face-4 :inherit 'outline-4)
   (markdown-header-face-5 :inherit 'outline-5)
   (markdown-header-face-6 :inherit 'outline-6)
   (markdown-header-delimiter-face :foreground base5)
   ;; inline structure
   (link :foreground aqua :underline t)
   (org-link :foreground aqua :underline t)
   (markdown-link-face :foreground aqua)
   (markdown-url-face :foreground base6 :underline t)
   (markdown-bold-face :foreground base8 :weight 'bold)
   (markdown-italic-face :foreground gold :slant 'italic)
   (markdown-inline-code-face :foreground peach :background base1)
   ((org-code &override) :foreground peach)
   (markdown-blockquote-face :foreground sage :slant 'italic)
   ((org-quote &override) :foreground sage :slant 'italic)
   (markdown-list-face :foreground coral)
   (markdown-gfm-checkbox-face :foreground gold :weight 'bold)
   (markdown-metadata-key-face :foreground coral)
   (markdown-metadata-value-face :foreground fg-alt)
   ((org-tag &override) :foreground sage)
   ((org-document-title &override) :foreground base8 :weight 'bold)))

;;; doom-vapor-night-theme.el ends here
