;;; doom-amber-crt-theme.el --- Amber phosphor monochrome -*- no-byte-compile: t; -*-
;;; Commentary:
;;; Same palette as alacritty / dwm bar / firefox: everything is a shade of
;;; amber, brightness (and bold) carries the meaning, like an IBM 5151 era CRT.
;;; Code:
(require 'doom-themes)

(def-doom-theme doom-amber-crt
    "Amber phosphor monochrome CRT."

  ;; name        default   256       16
  ((bg         '("#140c00" nil       nil            ))
   (bg-alt     '("#0c0700" nil       nil            ))
   (base0      '("#0c0700" "black"   "black"        ))
   (base1      '("#1f1400" nil       nil            ))
   (base2      '("#2e1e00" nil       nil            ))
   (base3      '("#3d2800" nil       nil            ))
   (base4      '("#664200" nil       nil            ))
   (base5      '("#805300" nil       nil            ))
   (base6      '("#996300" nil       nil            ))
   (base7      '("#b37400" nil       nil            ))
   (base8      '("#ffe6a6" "white"   "white"        ))
   (fg         '("#ffb000" "white"   "white"        ))
   (fg-alt     '("#cc8a1a" "white"   "white"        ))

   (grey       base5)
   (red        '("#ff7a1a" "#ff7a1a" "red"          ))
   (orange     '("#ff9933" "#ff9933" "brightred"    ))
   (green      '("#ffcc4d" "#ffcc4d" "green"        ))
   (teal       '("#ffd966" "#ffd966" "brightgreen"  ))
   (yellow     '("#ffc233" "#ffc233" "yellow"       ))
   (blue       '("#fff4d6" "#fff4d6" "brightblue"   ))
   (dark-blue  '("#b37400" "#b37400" "blue"         ))
   (magenta    '("#e6a31a" "#e6a31a" "magenta"      ))
   (violet     '("#d98f00" "#d98f00" "brightmagenta"))
   (cyan       '("#ffbf33" "#ffbf33" "brightcyan"   ))
   (dark-cyan  '("#a86e00" "#a86e00" "cyan"         ))

   ;; accents for document structure only (headings, links, quotes, tags);
   ;; code stays monochrome amber
   (coral      '("#ff6f59" "#ff6f59" "red"          ))
   (gold       '("#ffd24d" "#ffd24d" "yellow"       ))
   (sage       '("#c2c96b" "#c2c96b" "green"        ))
   (peach      '("#ffa26b" "#ffa26b" "brightred"    ))
   (aqua       '("#8fc7b0" "#8fc7b0" "cyan"         ))
   (rose       '("#e89a9a" "#e89a9a" "magenta"      ))

   ;; face categories -- required for all themes
   (highlight      fg)
   (vertical-bar   base4)
   (selection      base3)
   (builtin        yellow)
   (comments       base5)
   (doc-comments   base6)
   (constants      orange)
   (functions      base8)
   (keywords       base8)
   (methods        base8)
   (operators      fg)
   (type           yellow)
   (strings        green)
   (variables      fg)
   (numbers        orange)
   (region         base3)
   (error          red)
   (warning        orange)
   (success        green)
   (vc-modified    base6)
   (vc-added       green)
   (vc-deleted     red)

   (modeline-fg     bg)
   (modeline-bg     fg)
   (modeline-bg-inactive base1))

  ;; --- extra faces ------------------------
  (((line-number &override) :foreground base4)
   ((line-number-current-line &override) :foreground fg :weight 'bold)
   ((font-lock-keyword-face &override) :weight 'bold)
   ((font-lock-function-name-face &override) :weight 'bold)
   (cursor :background fg)
   ;; inverted mode-line, like the selected tag in the dwm bar
   (mode-line :background modeline-bg :foreground modeline-fg)
   (mode-line-inactive :background modeline-bg-inactive :foreground base6)
   (doom-modeline-bar :background bg)
   (doom-modeline-buffer-file :foreground modeline-fg :weight 'bold)
   (doom-modeline-buffer-path :foreground modeline-fg)
   (doom-modeline-project-dir :foreground modeline-fg :weight 'bold)
   (doom-modeline-info :foreground modeline-fg)
   ;; dired: same idea as ls in the terminal
   (dired-directory :foreground blue :weight 'bold)
   (dired-symlink :foreground dark-cyan :weight 'bold :underline t)
   ;; headings: one hue per level (org and markdown share them)
   (outline-1 :foreground base8 :weight 'bold)
   (outline-2 :foreground coral :weight 'bold)
   (outline-3 :foreground gold  :weight 'bold)
   (outline-4 :foreground sage  :weight 'bold)
   (outline-5 :foreground peach :weight 'bold)
   (outline-6 :foreground aqua  :weight 'bold)
   (outline-7 :foreground rose  :weight 'bold)
   (outline-8 :foreground base7 :weight 'bold)
   ((org-level-1 &override) :inherit 'outline-1 :foreground base8)
   ((org-level-2 &override) :inherit 'outline-2 :foreground coral)
   ((org-level-3 &override) :inherit 'outline-3 :foreground gold)
   ((org-level-4 &override) :inherit 'outline-4 :foreground sage)
   ((org-level-5 &override) :inherit 'outline-5 :foreground peach)
   ((org-level-6 &override) :inherit 'outline-6 :foreground aqua)
   (markdown-header-face-1 :inherit 'outline-1)
   (markdown-header-face-2 :inherit 'outline-2)
   (markdown-header-face-3 :inherit 'outline-3)
   (markdown-header-face-4 :inherit 'outline-4)
   (markdown-header-face-5 :inherit 'outline-5)
   (markdown-header-face-6 :inherit 'outline-6)
   (markdown-header-delimiter-face :foreground base5)
   ;; inline structure
   (link :foreground aqua :underline t)
   (org-link :foreground aqua :underline t)
   (markdown-link-face :foreground aqua)
   (markdown-url-face :foreground base6 :underline t)
   (markdown-bold-face :foreground base8 :weight 'bold)
   (markdown-italic-face :foreground gold :slant 'italic)
   (markdown-inline-code-face :foreground peach :background base1)
   ((org-code &override) :foreground peach)
   (markdown-blockquote-face :foreground sage :slant 'italic)
   ((org-quote &override) :foreground sage :slant 'italic)
   (markdown-list-face :foreground coral)
   (markdown-gfm-checkbox-face :foreground gold :weight 'bold)
   (markdown-metadata-key-face :foreground coral)
   (markdown-metadata-value-face :foreground fg-alt)
   ((org-tag &override) :foreground sage)
   ((org-document-title &override) :foreground base8 :weight 'bold)))

;;; doom-amber-crt-theme.el ends here
