#!/usr/bin/env bash

main() {
    source ~/Projects/Dotfiles/scripts/color.sh
    [[ $BUTTON = 2 ]] && setsid -t st -e e ~/Projects/Dotfiles/scripts/battery

    local full_charged="fully-charged"
    local charging="charging"
    local discharge="discharging"

    local full_power_status=$(upower -i $(upower -e | grep BAT) | grep --color=never state)
    local power_status=${full_power_status/state: /}

    percentage=$(cat /sys/class/power_supply/BAT0/capacity)

    [ $power_status = $full_charged ] && printf "🔌 ${percentage}%s" %
    [ $power_status = $charging ] && echo "⚡ $percentage%"

    if [ $power_status = $discharge ]; then
        [  $percentage -lt 15 ] && echo "🪫 $percentage%" && return
        echo "🔋 $percentage%"
    fi
}

main
