#!/usr/bin/env bash

main() {
    local full_charged="fully-charged"
    local charging="charging"
    local discharge="discharging"

    local full_power_status=$(upower -i $(upower -e | grep BAT) | grep --color=never state)
    local power_status=${full_power_status/state: /}

    percentage=$(cat /sys/class/power_supply/BAT0/capacity)

    [ $power_status = $full_charged ] && echo "$percentage%(F)"
    [ $power_status = $charging ] && echo "$percentage%(C)"
    [ $power_status = $discharge ] && echo "$percentage%"
}

main
