#!/usr/bin/env bash

screenshot_path=$HOME/Documents/Pictures/screenshots/
action=$(echo -e "gui\nfull" | dmenu)
case $action in
    "gui")
        flameshot gui -p $(realpath $screenshot_path)
        ;;
    "full")
        flameshot full -c -p $screen_path
        ;;
    *)
        ;;
esac
